### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by clubby789** [fieldraccoon/HostEnumerator#2]
- Flags for which scans to run
- Ratelimiting
- More wordlist options (for light fuzzing vs heavy fuzzing)
- Hosts/ports file for mass scanning

**Comment by fieldraccoon** [comment]
wordlist options will be coming soon TM, and so is which scans, eg I will do like you can just do, -d for directories for example

**Comment by fieldraccoon** [comment]
thanks for the suggestions. taking them into consideration.
