### ISSUE TITLE
Why scan with two different tools?

### ISSUE THREAD

**Issue by clubby789** [fieldraccoon/HostEnumerator#3]
https://github.com/fieldraccoon/LinuxEnumerator/blob/25b2b3cb1de5d1e1a78240d72f20cd1ad149bd8e/Enumerator.sh#L143-L144

As far as I can tell it's 2x the time for the same results

**Comment by fieldraccoon** [comment]
it was more a variety idk il probs get rid of it all allow people to set maybe a default option to which tool they want to use. Likely il get rid of one
